name: docu_site
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  country_picker: ^2.0.27
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.1.0
  flutter_slidable: ^4.0.1
  flutter_svg: ^2.2.0
  flutter_xlider: ^3.5.0
  get: ^4.7.2
  intl: any
  percent_indicator: ^4.2.5
  pinput: ^5.0.1
  sheet: ^1.0.0
  smooth_page_indicator: ^1.2.1
  syncfusion_flutter_charts: ^30.2.7
  syncfusion_flutter_gauges: ^30.2.7
  textfield_tags: ^3.0.1
  firebase_app_check: ^0.3.0+2
  http: ^1.2.1
  image: ^4.2.0
  google_fonts: ^6.2.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.2
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.2
#  camera: ^0.10.6
  flutter_tts: ^3.6.0
  lucide_icons: ^0.257.0
  font_awesome_flutter: ^10.5.0
  sign_in_with_apple:
  image_picker: ^1.0.7
  permission_handler: ^11.3.1
  path: ^1.8.3
  file_picker: ^8.1.2
  flutter_emoji: ^2.5.0
  video_player: ^2.9.1
  firebase_messaging: ^15.0.0
  shared_preferences: ^2.2.2
#  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/app_icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYREGULAR.OTF
          weight: 400
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYBOLD.OTF
          weight: 700

flutter_assets:
  assets_path: assets/
  output_path: lib/constants/
  filename: app_images.dart
  field_prefix: ""
