name: docu_site
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  country_picker: ^2.0.27
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.1.0
  flutter_slidable: ^4.0.1
  flutter_svg: ^2.2.0
  flutter_xlider: ^3.5.0
  get: ^4.7.2
  intl: any
  percent_indicator: ^4.2.5
  pinput: ^5.0.1
  sheet: ^1.0.0
  smooth_page_indicator: ^1.2.1
  syncfusion_flutter_charts: ^30.2.7
  syncfusion_flutter_gauges: ^30.2.7
  textfield_tags: ^3.0.1
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYREGULAR.OTF
          weight: 400
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/sf-pro-display/SFPRODISPLAYBOLD.OTF
          weight: 700

flutter_assets:
  assets_path: assets/
  output_path: lib/constants/
  filename: app_images.dart
  field_prefix: ""
