// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfOyb24kP58XR6MrdGiu8w9co2UPgCxpg',
    appId: '1:1072828557755:web:656919ae3a83aca6523c9e',
    messagingSenderId: '1072828557755',
    projectId: 'docusite-app',
    authDomain: 'docusite-app.firebaseapp.com',
    storageBucket: 'docusite-app.firebasestorage.app',
    measurementId: 'G-HBK2B824VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtHexsSgK6C9uDCxcPQpyO7BDZuMblKYA',
    appId: '1:1072828557755:android:7bce26cd3486fd7f523c9e',
    messagingSenderId: '1072828557755',
    projectId: 'docusite-app',
    storageBucket: 'docusite-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu377UyQQwnV51b-iAGifHOQPYa31VQK8',
    appId: '1:1072828557755:ios:ce84a29980f9f85a523c9e',
    messagingSenderId: '1072828557755',
    projectId: 'docusite-app',
    storageBucket: 'docusite-app.firebasestorage.app',
    iosBundleId: 'com.example.docsuite',
  );
}
